# Persistent Volume for MySQL
apiVersion: v1
kind: PersistentVolume
metadata:
  name: notification-db-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/notification-db"
---
# Persistent Volume Claim for MySQL
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: notification-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
# MySQL Deployment for Borrow Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-db
spec:
  selector:
    matchLabels:
      app: notification-db
  template:
    metadata:
      labels:
        app: notification-db
    spec:
      containers:
      - name: mysql
        image: mysql:8
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: rootpass
        - name: MYSQL_DATABASE
          value: notificationdb
        - name: MYSQL_USER
          value: user
        - name: MYSQL_PASSWORD
          value: password
        volumeMounts:
        - name: notification-db-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: notification-db-storage
        persistentVolumeClaim:
          claimName: notification-db-pvc
---
# MySQL Service
apiVersion: v1
kind: Service
metadata:
  name: notification-db
spec:
  selector:
    app: notification-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP